# Generated by Django 6.0.2 on 2026-05-07 04:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('amount_requested', models.FloatField(default=0)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('current_step', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('approved_amount', models.FloatField(default=0)),
                ('interest_rate', models.FloatField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.issuer')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='core.loanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField(default=0)),
                ('payment_method', models.TextField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_payments', to='core.loan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payments', to='core.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('index_number', models.TextField(max_length=25)),
                ('reference_number', models.TextField(max_length=25)),
                ('ghana_card_number', models.TextField(max_length=40, validators=[django.core.validators.RegexValidator(inverse_match=False, message='Invalid Ghana Card format (Expected: GHA-XXXXXXXXX-X)', regex='^GHA-\\d{9}-\\d$')])),
                ('passport_photo', models.FileField(null=True, upload_to='passport_photo/')),
                ('level', models.TextField(default='100', max_length=4)),
                ('phone_number', models.TextField(max_length=30)),
                ('program', models.TextField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='core.student'),
        ),
        migrations.AddField(
            model_name='loan',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='core.student'),
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('document_type', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(null=True, upload_to='loan_documents/')),
                ('status', models.TextField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.loanapplication')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.student')),
            ],
        ),
    ]
