# Generated by Django 6.0.2 on 2026-05-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passport_photo',
            field=models.FileField(blank=True, null=True, upload_to='passport_photo/'),
        ),
    ]
