# Generated by Django 6.0.2 on 2026-05-13 12:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_passport_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='index_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passport_photo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
        migrations.RemoveField(
            model_name='student',
            name='reference_number',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='media/profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ghana_card_number',
            field=models.TextField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=False, message='Invalid Ghana Card format (Expected: GHA-XXXXXXXXX-X)', regex='^GHA-\\d{9}-\\d$')]),
        ),
        migrations.CreateModel(
            name='AccountVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplicationInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('first_names', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ghana_card_number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(inverse_match=False, message='Invalid Ghana Card format (Expected: GHA-XXXXXXXXX-X)', regex='^GHA-\\d{9}-\\d$')])),
                ('guardian_name', models.CharField(blank=True, max_length=255)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50)),
                ('guardian_phone_number', models.CharField(blank=True, max_length=50)),
                ('reference_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=False, message='Invalid Reference Number format (Expected: UEBXXXXXXX)', regex='UA\\d{7}')])),
                ('index_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(inverse_match=False, message='Invalid Index Number format (Expected: UEBXXXXXXX)', regex='UEB\\d{7}')])),
                ('program', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=255)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_information', to='core.loanapplication')),
            ],
        ),
    ]
