# Generated by Django 6.0.2 on 2026-05-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_student_index_number_remove_student_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='loan_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('disbursed', 'Funds Disbursed')], default='submitted', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
    ]
