# Generated by Django 6.0.2 on 2026-05-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_loanapplication_loan_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplicationinfo',
            name='surname',
        ),
        migrations.AddField(
            model_name='studentapplicationinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='studentapplicationinfo',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='status',
            field=models.TextField(blank=True, choices=[('uploaded', 'Uploaded'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=255),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='submitted', max_length=50),
        ),
    ]
