# Generated by Django 6.0.2 on 2026-05-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_studentapplicationinfo_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplicationinfo',
            name='surname',
            field=models.CharField(default='Sefah', max_length=255),
            preserve_default=False,
        ),
    ]
