# Generated by Django 6.0.2 on 2026-05-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_studentapplicationinfo_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(blank=True, choices=[('awaiting_disbursement', 'Awaiting Disbursement'), ('cancelled', 'Cancelled'), ('disbursed', 'Funds Disbursed')], max_length=50),
        ),
        migrations.AddField(
            model_name='loan',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('completed', 'Completed')], max_length=50),
        ),
    ]
