# Generated by Django 6.0.2 on 2026-07-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_loan_payment_status_alter_loan_issuer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(blank=True, choices=[('awaiting_disbursement', 'Awaiting Disbursement'), ('disbursed', 'Disbursed'), ('active', 'Active'), ('completed', 'completed'), ('cancelled', 'Cancelled')], max_length=50),
        ),
    ]
