# Generated by Django 6.0.2 on 2026-07-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_loan_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayment',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
