# Generated by Django 6.0.2 on 2026-07-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_loanpayment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=255),
        ),
    ]
