

class LogActionType:
    CREATE_USER = 'CREATE_USER'
    CHANGE_USER_ROLE = 'CHANGE_USER_ROLE'
    CHANGE_USER_STATUS = 'CHANGE_USER_STATUS'
    CHANGE_LOAN_STATUS = 'CHANGE_LOAN_STATUS'
    LOAN_APPROVAL = 'LOAN_APPROVAL'
    LOAN_REJECTION = 'LOAN_REJECTION'
    